name: cuts
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.8
  - matplotlib
  - scipy
  - numpy
  - pandas
  - pytorch=1.6.0
  - torchvision=0.7.0
  - jupyterlab
  - ipywidgets
  - scikit-learn
  - jaxlib
  - jax
  - py-xgboost
